<a href="https://colab.research.google.com/github/JoaLiriano/messy-data-cleaning-python/blob/main/Data_Cleaning_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
data_import = pd.read_csv('/content/drive/MyDrive/Exercises/data_cleaning_challenge.csv')
data_import

,Row Type,Iter Number,Power1,Speed1,Speed2,Electricity,Effort,Weight,Torque,Unnamed: 9,Unnamed: 10
0,first name: Person,last name: Human,date: end of time,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Row Type,Iter Number,Power1,Speed1,Speed2,Electricity,Effort,Weight,Torque,NaN,NaN
3,Iter,1,360,108,863,599,680,442,982,NaN,NaN
4,Iter,2,684,508,613,241,249,758,639,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
76372,Iter,6,879,73,977,680,500,395,863,NaN,NaN
76373,Average,979,641,531,374,448,407,185,439,NaN,NaN
76374,Maximum,783,172,941,53,982,217,963,502,NaN,NaN
76375,Std.Dev.,221,112,717,630,239,561,142,909,NaN,NaN
76376,Total,429,-,-,-,-,847,583,407,NaN,NaN

In [ ]:
drop_extra = data_import.drop(columns=['Unnamed: 9','Unnamed: 10'])
drop_extra

,Row Type,Iter Number,Power1,Speed1,Speed2,Electricity,Effort,Weight,Torque
0,first name: Person,last name: Human,date: end of time,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Row Type,Iter Number,Power1,Speed1,Speed2,Electricity,Effort,Weight,Torque
3,Iter,1,360,108,863,599,680,442,982
4,Iter,2,684,508,613,241,249,758,639
...,...,...,...,...,...,...,...,...,...
76372,Iter,6,879,73,977,680,500,395,863
76373,Average,979,641,531,374,448,407,185,439
76374,Maximum,783,172,941,53,982,217,963,502
76375,Std.Dev.,221,112,717,630,239,561,142,909
76376,Total,429,-,-,-,-,847,583,407

In [ ]:
drop_nans = drop_extra[drop_extra["Row Type"].notna()]
drop_nans

,Row Type,Iter Number,Power1,Speed1,Speed2,Electricity,Effort,Weight,Torque
0,first name: Person,last name: Human,date: end of time,NaN,NaN,NaN,NaN,NaN,NaN
2,Row Type,Iter Number,Power1,Speed1,Speed2,Electricity,Effort,Weight,Torque
3,Iter,1,360,108,863,599,680,442,982
4,Iter,2,684,508,613,241,249,758,639
5,Iter,3,365,126,825,407,855,164,86
...,...,...,...,...,...,...,...,...,...
76372,Iter,6,879,73,977,680,500,395,863
76373,Average,979,641,531,374,448,407,185,439
76374,Maximum,783,172,941,53,982,217,963,502
76375,Std.Dev.,221,112,717,630,239,561,142,909
76376,Total,429,-,-,-,-,847,583,407

In [ ]:
column_values = []
counter = 0

for i in drop_nans['Row Type']:
  if "first name" in i:
    counter += 1
    column_values.append(counter)

In [ ]:
iter_cols = drop_nans.copy()

# Create a boolean series indicating where 'first name' is found
is_first_name = iter_cols['Row Type'].str.contains("first name", na=False)

# Create a series where a number is assigned only when 'first name' is found, otherwise NaN.
# The cumulative sum of the boolean series gives the iteration number for each 'first name' row.
iteration_series = is_first_name.cumsum().where(is_first_name)

# Forward-fill the NaN values with the last valid iteration number.
# This propagates the iteration number to all rows within a block.
iter_cols['Iteration'] = iteration_series.ffill()

iter_cols

,Row Type,Iter Number,Power1,Speed1,Speed2,Electricity,Effort,Weight,Torque,Iteration
0,first name: Person,last name: Human,date: end of time,NaN,NaN,NaN,NaN,NaN,NaN,1.0
2,Row Type,Iter Number,Power1,Speed1,Speed2,Electricity,Effort,Weight,Torque,1.0
3,Iter,1,360,108,863,599,680,442,982,1.0
4,Iter,2,684,508,613,241,249,758,639,1.0
5,Iter,3,365,126,825,407,855,164,86,1.0
...,...,...,...,...,...,...,...,...,...,...
76372,Iter,6,879,73,977,680,500,395,863,5994.0
76373,Average,979,641,531,374,448,407,185,439,5994.0
76374,Maximum,783,172,941,53,982,217,963,502,5994.0
76375,Std.Dev.,221,112,717,630,239,561,142,909,5994.0
76376,Total,429,-,-,-,-,847,583,407,5994.0

In [ ]:
drop_extra_column_name_rows = iter_cols[iter_cols["Row Type"] != "Row Type"]
drop_extra_column_name_rows

,Row Type,Iter Number,Power1,Speed1,Speed2,Electricity,Effort,Weight,Torque,Iteration
0,first name: Person,last name: Human,date: end of time,NaN,NaN,NaN,NaN,NaN,NaN,1.0
3,Iter,1,360,108,863,599,680,442,982,1.0
4,Iter,2,684,508,613,241,249,758,639,1.0
5,Iter,3,365,126,825,407,855,164,86,1.0
6,Iter,4,764,594,304,718,278,674,774,1.0
...,...,...,...,...,...,...,...,...,...,...
76372,Iter,6,879,73,977,680,500,395,863,5994.0
76373,Average,979,641,531,374,448,407,185,439,5994.0
76374,Maximum,783,172,941,53,982,217,963,502,5994.0
76375,Std.Dev.,221,112,717,630,239,561,142,909,5994.0
76376,Total,429,-,-,-,-,847,583,407,5994.0

In [ ]:
name_dataframe = drop_extra_column_name_rows[drop_extra_column_name_rows["Row Type"].str.contains('first name')]
name_dataframe.drop(columns=['Speed1','Speed2','Electricity','Effort','Weight','Torque'], inplace=True)
name_dataframe.rename(columns={'Row Type':'First Name', 'Iter Number':'Last Name','Power1':'Date'}, inplace=True)
name_dataframe['First Name'] = name_dataframe['First Name'].str[12:]
name_dataframe['Last Name'] = name_dataframe['Last Name'].str[11:]
name_dataframe['Date'] = name_dataframe['Date'].str[6:]
name_dataframe

/tmp/ipykernel_7594/3403728233.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  name_dataframe.drop(columns=['Speed1','Speed2','Electricity','Effort','Weight','Torque'], inplace=True)
/tmp/ipykernel_7594/3403728233.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  name_dataframe.rename(columns={'Row Type':'First Name', 'Iter Number':'Last Name','Power1':'Date'}, inplace=True)
/tmp/ipykernel_7594/3403728233.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  name_dataframe['First Name'] = name_dataframe['First Name'].str[12:]
/tmp/ipykernel_7594/3403728233.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  name_dataframe['Last Name'] = name_dataframe['Last Name'].str[11:]
/tmp/ipykernel_7594/3403728233.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  name_dataframe['Date'] = name_dataframe['Date'].str[6:]

      First Name Last Name         Date  Iteration
0         Person     Human  end of time        1.0
14        Person     Human  end of time        2.0
28        Person     Human  end of time        3.0
42        Person     Human  end of time        4.0
56        Person     Human  end of time        5.0
...          ...       ...          ...        ...
76309     Person     Human  end of time     5990.0
76322     Person     Human  end of time     5991.0
76336     Person     Human  end of time     5992.0
76350     Person     Human  end of time     5993.0
76364     Person     Human  end of time     5994.0

[5994 rows x 4 columns]

In [ ]:
no_name_dataframe = drop_extra_column_name_rows[~drop_extra_column_name_rows["Row Type"].str.contains('first name')]
no_name_dataframe

,Row Type,Iter Number,Power1,Speed1,Speed2,Electricity,Effort,Weight,Torque,Iteration
3,Iter,1,360,108,863,599,680,442,982,1.0
4,Iter,2,684,508,613,241,249,758,639,1.0
5,Iter,3,365,126,825,407,855,164,86,1.0
6,Iter,4,764,594,304,718,278,674,774,1.0
7,Iter,5,487,97,593,206,779,800,123,1.0
...,...,...,...,...,...,...,...,...,...,...
76372,Iter,6,879,73,977,680,500,395,863,5994.0
76373,Average,979,641,531,374,448,407,185,439,5994.0
76374,Maximum,783,172,941,53,982,217,963,502,5994.0
76375,Std.Dev.,221,112,717,630,239,561,142,909,5994.0
76376,Total,429,-,-,-,-,847,583,407,5994.0

In [ ]:
final_dataframe = pd.merge(left=name_dataframe, right=no_name_dataframe, how='inner', on='Iteration')
final_dataframe = final_dataframe.drop(columns=['Iteration'])
final_dataframe

,First Name,Last Name,Date,Row Type,Iter Number,Power1,Speed1,Speed2,Electricity,Effort,Weight,Torque
0,Person,Human,end of time,Iter,1,360,108,863,599,680,442,982
1,Person,Human,end of time,Iter,2,684,508,613,241,249,758,639
2,Person,Human,end of time,Iter,3,365,126,825,407,855,164,86
3,Person,Human,end of time,Iter,4,764,594,304,718,278,674,774
4,Person,Human,end of time,Iter,5,487,97,593,206,779,800,123
...,...,...,...,...,...,...,...,...,...,...,...,...
46404,Person,Human,end of time,Iter,6,879,73,977,680,500,395,863
46405,Person,Human,end of time,Average,979,641,531,374,448,407,185,439
46406,Person,Human,end of time,Maximum,783,172,941,53,982,217,963,502
46407,Person,Human,end of time,Std.Dev.,221,112,717,630,239,561,142,909
46408,Person,Human,end of time,Total,429,-,-,-,-,847,583,407